### ISSUE TITLE
This is cool! Can I join?

### ISSUE THREAD

**Issue by fkornel** [Pixel8edstudios/The-Pixelnet#2]
Hi There!

I am interested in your development efforts. Can I join to you?

Thanks in advance,
Kornél

**Comment by Pixel8edstudios** [comment]
Yes! If you are interested in PixelNet development, please friend me on discord with Pixel#2234

I would love to hear from you!

**Comment by fkornel** [comment]
Hi!

Awesome, I tried to get in contact with you on discord, but it says, that you blocked/disabled any incoming friend requests, so here is my discord:
fkornel#4073

Bests,
K

**Comment by Pixel8edstudios** [comment]
Alright, I'll make sure to get to it!

**Comment by Pixel8edstudios** [comment]
Hello! I would also like to mention that I have friended you on Discord. Please check out your Discord, and i'd be happy to see how you can help the project!

--Pixel8edstudios

**Comment by Pixel8edstudios** [comment]
Also, let me know if you'd like to meet some time! Thank you!
